import 'package:flutter/material.dart';
import 'package:mix/mix.dart';
import 'package:smash_app/domain/models/suggestion_result.dart';
import 'package:smash_app/presentation/theme/app_colors.dart';
import 'package:smash_app/presentation/theme/app_spacing.dart';
import 'package:smash_app/presentation/theme/app_text_styles.dart';
import 'package:smash_app/presentation/widgets/atoms/message_card.dart';

/// Organism: the 3 message suggestions, plus a small indicator of which
/// fallback stage produced them (useful during manual testing/demoing the
/// backend's fallback chain, see `api/CLAUDE.md`).
class SuggestionsList extends StatelessWidget {
  const SuggestionsList({super.key, required this.result});

  final SuggestionResult result;

  String get _sourceLabel => switch (result.source) {
    SuggestionSource.llm => 'Generated by AI',
    SuggestionSource.cache => 'From a previous AI response',
    SuggestionSource.staticFallback => 'Suggested message',
  };

  @override
  Widget build(BuildContext context) {
    final gap = AppSpacing.sm.resolve(context);
    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        StyledText(
          _sourceLabel,
          style: Style(
            $text.style.ref(AppTextStyles.caption),
            $text.color.ref(AppColors.textMuted),
          ),
        ),
        SizedBox(height: gap),
        for (final message in result.messages) ...[
          MessageCard(message: message),
          SizedBox(height: gap),
        ],
      ],
    );
  }
}
